//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactTestingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Table
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
    
        public virtual Customer_Table Customer_Table { get; set; }
        public virtual Product_Table Product_Table { get; set; }
        public virtual Store_Table Store_Table { get; set; }
    }
}
